name = "shorturl-007"
main = "src/index.js"
compatibility_date = "2023-04-13"
node_compat = true

[[kv_namespaces]]
binding = "LINKS"
id = "e606cd00ac494618ae639fa452582088" ## Change it to yours
[build]
command = "npm run build"
[vars]
USERNAME = "bee" # Change it and don't expose it in this file
PASSWORD = "hive" # Change it and don't expose it in this file
JWT_SECRET = "beehive" # Change it and don't expose it in this file
DEFAULT_PAGE = "https://www.omniweblinks.com/" # Change it
RECORD_CLICKS = true
FE_ADMIN_DOMAIN = "https://www.omniweblinks.com/" #Remember to replace it with your admin domain, important for cross origin allowlist




